=== Z3nitt/LLMM_Entornos/xml/fichas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="fichas">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="ficha" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="longitud"></xs:element>
                        <xs:element name="apellido" type="longitud"></xs:element>
                        <xs:element name="edad">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="1"></xs:minInclusive>
                                    <xs:maxInclusive value="130"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="numero" type="xs:integer" use="required"></xs:attribute>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- Creacion de un metodo llamado longitud para no tener que repetir esto en el codigo-->
<xs:simpleType name="longitud">
    <xs:restriction base="xs:string">
        <xs:minLength value="1"></xs:minLength>
        <xs:maxLength value="15"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

















</xs:schema>

=== Z3nitt/LLMM_Entornos/xml/fichas.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fichas.xsd">
    <ficha numero="1">
        <nombre>Ana</nombre>
        <apellido>Ruiz</apellido>
        <edad>23</edad>
    </ficha>
    <ficha numero="2">
        <nombre>Mario</nombre>
        <apellido>Sanchez</apellido>
        <edad>26</edad>
    </ficha>
</fichas>

<!-- Quiero validar el documento XML anterior. Teniendo en cuenta que la edad tiene que ser un valor comprendido entre 1 y 130 (ambos valores incluidos). AdemÃ¡s, tanto el nombre como el apellido tienen 15 caracteres.-->
